# Site settings
title: Rishabh-Bhatt-Portfolio
description: A portfolio website for Rishabh-Bhatt-Portfolio
# baseurl: "rishabh"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "https://rishabhbhatt009.github.io"

# User settings
username: Rishabh Bhatt
user_description: I am an experienced developer, I write code that tackles real-world problems with data driven solutions. I have worked with fortune 500 clients across continents & helped them use data to uncover key insights & drive successful business strategies.
user_title: Developer & Data Scientist
email: rishabhbhatt.app@gmail.com
twitter_username: 
github_username: rishabhbhatt009
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
