# Site settings
title: Rishabh-Bhatt-Portfolio
description: A portfolio website for Rishabh-Bhatt-Portfolio
# baseurl: "rishabh"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "https://rishabhbhatt009.github.io"

# User settings
username: Rishabh Bhatt
user_description: NaN
user_title: NaN
email: rishabhbhatt.app@gmail.com
twitter_username: 
github_username: rishabhbhatt009
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
